<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1546005040671" stop="1546005098166" version="1.5.4" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Surefire suite : Surefire test</name>
    <title>Surefire suite : Surefire test</title>
    <test-cases>
        <test-case start="1546005048677" stop="1546005088004" status="passed">
            <name>firsttest</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Surefire suite"/>
                <label name="testGroup" value="Surefire test"/>
                <label name="testClass" value="TestClass"/>
                <label name="testMethod" value="firsttest"/>
                <label name="host" value="vprybeha-w7"/>
                <label name="thread" value="3380@vprybeha-w7.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1546005093978" stop="1546005097189" status="broken">
            <name>secondtest</name>
            <failure>
                <message>NewException: Assertion finished false</message>
                <stack-trace>SupportClasses.NewException: Assertion finished false
	at TestClass.secondtest(TestClass.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Surefire suite"/>
                <label name="testGroup" value="Surefire test"/>
                <label name="testClass" value="TestClass"/>
                <label name="testMethod" value="secondtest"/>
                <label name="host" value="vprybeha-w7"/>
                <label name="thread" value="3380@vprybeha-w7.main(1)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
